spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.56.2:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=carlos
spring.datasource.password=Dud4#2011

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#define o tempo máximo que uma conexão fica ativa
#spring.datasource.hikari.idle-timeout=10000
#tamanho máximo do pool de conexões que podem ser criadas em runtime
#spring.datasource.hikari.maximum-pool-size=20
#minimo de conexões que devem ser mantidas
#spring.datasource.hikari.minimum-idle=3